name: your_journal

description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # For IOS style iconswflutter
  cupertino_icons: ^1.0.6

  # For showing calendar
  table_calendar: ^3.0.9

  # For spl lite
  sqflite: ^2.3.0

  # For finding commonly used locations on the filesystem
  path_provider: ^2.1.1

  # For using along path_provider
  path: ^1.8.3

  # For date manuplation
  intl: ^0.19.0

  # For showing feed back
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/book.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/book.png"
  windows:
    generate: true
    image_path: "assets/images/book.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/book.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Italianno
      fonts:
        - asset: assets/fonts/Italianno-Regular.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700